name: CI

on:
  push:
    tags:
      - v*

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Permissions
        run: chmod 777 -R .
      - uses: ju5t/docker-run-action@v0.0.3
        with:
          image: sensson/rpmbuild:rockylinux-8
          options: -v ${{ github.workspace }}:/srv -e RELEASE=${{ github.ref }}
      - name: Dependencies
        run: pip install --user cloudsmith-cli
      - name: Deploy
        run: bash deploy-rpm.sh
        env:
          APIKEY: ${{ secrets.APIKEY }}

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Script
        run: |
          mkdir -p .debpkg/var/lib/Acronis/mysql/
          cp mysqlbackup.sh .debpkg/var/lib/Acronis/mysql/
          cp mysqlfreeze.sh .debpkg/var/lib/Acronis/mysql/
          cp mysqlthaw.sh .debpkg/var/lib/Acronis/mysql/
          cp mysql.conf .debpkg/var/lib/Acronis/mysql/
          cp functions.sh .debpkg/var/lib/Acronis/mysql/
      - uses: jiro4989/build-deb-action@v3
        with:
          package: acronis-mysql-scripts
          package_root: .debpkg
          maintainer: Sensson
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          desc: 'Backups scripts to be used by Acronis to make backups of MySQL.'
      - name: Dependencies
        run: pip install --user cloudsmith-cli
      - name: Deploy
        run: bash deploy-deb.sh
        env:
          APIKEY: ${{ secrets.APIKEY }}
      
    
    
